version: "3.9"

services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      game-net:
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    
  gamescript:
    build: ./game/
    networks:
      game-net:
    depends_on:
      - "broker"

  nodered:
    build: ./dashboard/
    networks:
      game-net:
    ports:
      - "80:1880"
    volumes:
      - ./dashboard:/data
    depends_on:
      - "broker"

  colour_detector:
    build: ./detector/
    networks:
      game-net:
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    
    depends_on:
      - "broker"
networks:
  game-net:    
